# Generated by Django 5.2.1 on 2026-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoelDigitalsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
