# Generated by Django 5.2.1 on 2026-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JoelDigitalsApp', '0003_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
