# Generated by Django 5.2.1 on 2026-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoelDigitalsApp', '0005_statussubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('user_ids', models.JSONField(blank=True, help_text='Liste von User-IDs; leer/None = Broadcast an alle abonnierten Geraete', null=True)),
                ('url', models.URLField(blank=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
