"""
Django settings for joel_digitals project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import environ
env = environ.Env()
environ.Env.read_env()  # Liest die .env-Datei

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7!2q=m-knqi1a#+7()qky&!*(*5k3^9(bb)*koh_y$&&i7x$da'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['joel-digitals.de', 'www.joel-digitals.de', 'joel-digitals.onrender.com',
    '127.0.0.1', 
    'localhost',
    'download.joel-digitals.de',
    'blog.joel-digitals.de',
    'shop.joel-digitals.de',
    ]

OAUTH2_PROVIDER = {
    "SCOPES": {
        "read": "Read access",
    }
}

IMGBB_API_KEY = os.getenv("IMGBB_API_KEY")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.syndication',
    'ckeditor',
    'ckeditor_uploader',
    'main',
    'blog', 
    'contact',
    'shop_ourapps',  # Deine App für die Affiliate-Links
    'wiki',  # Deine Wiki-App
    'status',
    'download',
    'MobileApp',
    'chat',
    "reviews",
    'landingpages',
    'django.contrib.sites',
    'oauth2_provider',
    'admin_api',
    'autoupdate',
]

CKEDITOR_UPLOAD_PATH = "uploads/"

SITE_ID = 1

GA_PROPERTY_ID = "508800547"  # z.B. "123456789"

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/pfad/zu/service-account.json'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    "shop_ourapps.middleware.AffiliateRefMiddleware",
    "main.subdomain_middleware.SubdomainRedirectMiddleware",
]

ROOT_URLCONF = 'joel_digitals.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'main.context_processors.seo_data',
                'shop_ourapps.context_processor.affiliate_ref_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'joel_digitals.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db(),  # Liest die DATABASE_URL-Umgebungsvariable
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = 'Europe/Berlin'

LANGUAGE_CODE = 'de'

USE_I18N = True
USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ("en", _("English")),
    ("de", _("Deutsch")),
]

SEPA_CREDITOR_ID = os.getenv("SEPA_CREDITOR_ID", "DE39ZZZ00099999999")
SEPA_CREDITOR_NAME = "Joel Digitals"

TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER", "+4915253480270")
STATUS_HOTLINE_URL = "https://joel-digitals.de/de/status/hotline/"

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_AGE = 2419200  # 4 Wochen
SESSION_SAVE_EVERY_REQUEST = True

LOCALE_PATHS = [ BASE_DIR / "locale" ]

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Wenn du während der Entwicklung zusätzliche statische Dateien hast
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Dein static Ordner
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ADMIN_API_SECRET = os.getenv("ADMIN_API_SECRET", "admin-dev-secret-change-in-production")

CRON_SECRET = "jds-e-mails"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COMPANY_ADDRESS = 'Niederwiesstraße 20'
COMPANY_ZIP     = '66822'
COMPANY_CITY    = 'Lebach'

# SENDGRID as mail backend
EMAIL_BACKEND = "django_mailjet.backends.MailjetBackend"

MAILJET_API_KEY = "c3f43729e477c3cd3a4cfdd51ef6a2ba"
MAILJET_API_SECRET = "c06b2f2787d4a1ee5bf3c9821c8745c4"

DEFAULT_FROM_EMAIL = "no-reply@joel-digitals.com"
COMPANY_EMAIL_NO_REPLY = "no-reply@joel-digitals.com"
SUPPORT_EMAIL = "support@joel-digitals.com"
COMPANY_EMAIL = "info@joel-digitals.com"
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
SENDGRID_ECHO_TO_STDOUT = False

# SENDGRID as mail backend
#EMAIL_BACKEND = "django.core.mail.backends.base.BaseEmailBackend"
# Brevo API Key
#BREVO_API_KEY = os.environ.get("BREVO_API_KEY")
# Absender-Einstellungen
#DEFAULT_FROM_EMAIL = "info@joel-digitals.com"
#COMPANY_EMAIL = "info@joel-digitals.com"

MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

PAYPAL_CLIENT_ID = "AX7o18SnNzoZoP9IT2CYSoigBahHg-RBHlrysa1hf5iilolk434dHl_dXm8BrCl2af2XWF_gZ6-rgq5W"
PAYPAL_CLIENT_SECRET = "EBHffuUYFnB_U8x2fwv7HPuiX9uDBanpfO2mRGFL7lJCiaw986yRBaXok-J8zp5AJlC6s6Yg3A3LsPVX"
PAYPAL_ENVIRONMENT = "live"  # später "live" setzen

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
)

# Shared Secret für SSO
SSO_SHARED_SECRET = "Iay01SJILCeOtgo99wjdEf3b6kBULkYMD6e5mfiqZHGIdAUUs9uOvOcgF9utVRVp7oVL9bIDH9MdYLWMIuUk3ECmhFd7hXtfRiPDL0Eu2DffIjrIYD1bJkZgzzbBv9C5E9Fosg6aBu1mEliHcG39wYTbbdRk7YzyEEW7uvjRdDkWSeAtXuKHkm"

# JDS Management API
JDS_API_BASE_URL = os.getenv("JDS_API_BASE_URL", "https://jds-management.de")
JDS_TEAM_CODE = os.getenv("JDS_TEAM_CODE", "")
JDS_API_TOKEN = os.getenv("JDS_API_TOKEN", "")

# Cache aktivieren (falls noch nicht)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}