# Generated by Django 5.2.1 on 2025-06-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file_url',
            field=models.FileField(upload_to='downloads/'),
        ),
    ]
