# Generated by Django 4.2.30 on 2026-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_alter_download_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='external_link',
            field=models.URLField(blank=True, help_text='Externer Download-Link (hat Vorrang vor Datei-Upload)', null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
