# Generated by Django 5.2.1 on 2026-06-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_accesscode_accesssuspension_downloadpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpackageapp',
            name='download_link',
            field=models.URLField(blank=True, help_text='Direkter Link zum Download (hat Vorrang vor Download-Objekt)', max_length=500, verbose_name='Download-Link'),
        ),
    ]
