# Generated by Django 5.2 on 2025-05-04 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleswish',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='email',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='name',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleswish',
            name='wishes',
        ),
        migrations.AddField(
            model_name='saleswish',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saleswish',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='contact.salesentry'),
            preserve_default=False,
        ),
    ]
