# Generated by Django 5.2 on 2025-05-04 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_saleschatmessage_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleswish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
