# Generated by Django 5.2 on 2025-05-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_saleswish_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleschatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
