# Generated by Django 5.2.1 on 2025-06-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_timestamp_saleschatmessage_created_at'),
        ('shop_ourapps', '0017_voucher_voucherorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='app_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('other', 'Other')], default='web', max_length=10),
        ),
    ]
