# Generated by Django 5.2.1 on 2025-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_appointmenttype_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=10),
        ),
    ]
