# Generated by Django 5.2.1 on 2025-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mo'), (1, 'Di'), (2, 'Mi'), (3, 'Do'), (4, 'Fr'), (5, 'Sa'), (6, 'So')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
