# Generated by Django 5.2.1 on 2026-07-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_specialtimeslot_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtimeslot',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, sind an diesem Tag keine Termine buchbar'),
        ),
    ]
