from django.core.management.base import BaseCommand
from landingpages.models import LandingPage

CONTENT = {
    'jds-vereine': {
        'de': '<h2>Deine Vereinsverwaltung – endlich digital</h2><p>Schluss mit Papierkram. JDS Management fur Vereine bringt Mitgliederverwaltung, Events, Finanzen und Kommunikation in eine Plattform.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-users" style="font-size:2rem;color:var(--primary);"></i><h3>Mitglieder</h3><p>Zentral und DSGVO-konform verwalten, inkl. Beitragsstatus und Historie.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-calendar-check" style="font-size:2rem;color:var(--primary);"></i><h3>Events</h3><p>Veranstaltungen planen, Teilnehmer verwalten, Anmeldungen automatisieren.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-invoice" style="font-size:2rem;color:var(--primary);"></i><h3>Finanzen</h3><p>Beitrage automatisch berechnen, Zahlungen verfolgen, Kassenbuch fuhren.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-envelope" style="font-size:2rem;color:var(--primary);"></i><h3>Kommunikation</h3><p>Newsletter und E-Mails direkt aus der Software an deine Mitglieder.</p></div></div><p style="font-size:1.1rem;font-weight:600;text-align:center;">DSGVO-konform  |  Cloud-basiert  |  Keine versteckten Kosten  |  Telefon-Support</p>',
        'en': '<h2>Your Club Management – Finally Digital</h2><p>No more paperwork. JDS Management for clubs brings member management, events, finances and communication into one platform.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-users" style="font-size:2rem;color:var(--primary);"></i><h3>Members</h3><p>Central and GDPR-compliant management including fee status and history.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-calendar-check" style="font-size:2rem;color:var(--primary);"></i><h3>Events</h3><p>Plan events, manage attendees, automate signups.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-invoice" style="font-size:2rem;color:var(--primary);"></i><h3>Finance</h3><p>Auto-calculate fees, track payments, manage cash book.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-envelope" style="font-size:2rem;color:var(--primary);"></i><h3>Communication</h3><p>Newsletters and emails directly from the software to your members.</p></div></div><p style="font-size:1.1rem;font-weight:600;text-align:center;">GDPR-compliant  |  Cloud-based  |  No hidden costs  |  Phone support</p>',
        'cta_de': 'Jetzt Vereinssoftware testen', 'cta_en': 'Try Club Software'
    },
    'jds-management': {
        'de': '<h2>Eine Software fur dein gesamtes Business</h2><p>JDS Management vereint CRM, Projektmanagement, Rechnungsstellung und Analytics in einer Plattform. Spart Zeit, reduziert Fehler und bringt Struktur in deinen Workflow.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-address-book" style="font-size:2rem;color:var(--primary);"></i><h3>CRM</h3><p>Kunden und Leads verwalten, Pipeline tracken, Follow-ups automatisieren.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-tasks" style="font-size:2rem;color:var(--primary);"></i><h3>Projekte</h3><p>Aufgaben verteilen, Deadlines setzen, Fortschritt in Echtzeit.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-invoice" style="font-size:2rem;color:var(--primary);"></i><h3>Rechnungen</h3><p>Angebote und Rechnungen mit einem Klick erstellen und versenden.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-chart-line" style="font-size:2rem;color:var(--primary);"></i><h3>Analytics</h3><p>Umsatz, KPIs und Performance in Echtzeit im Blick.</p></div></div>',
        'en': '<h2>One Software for Your Entire Business</h2><p>JDS Management combines CRM, project management, invoicing and analytics in one platform. Saves time, reduces errors and brings structure to your workflow.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-address-book" style="font-size:2rem;color:var(--primary);"></i><h3>CRM</h3><p>Manage customers and leads, track pipeline, automate follow-ups.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-tasks" style="font-size:2rem;color:var(--primary);"></i><h3>Projects</h3><p>Assign tasks, set deadlines, real-time progress.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-invoice" style="font-size:2rem;color:var(--primary);"></i><h3>Invoicing</h3><p>Create and send quotes and invoices with one click.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-chart-line" style="font-size:2rem;color:var(--primary);"></i><h3>Analytics</h3><p>Real-time revenue, KPIs and performance overview.</p></div></div>',
        'cta_de': 'Jetzt Business-Software entdecken', 'cta_en': 'Discover Business Software'
    },
    'webentwicklung': {
        'de': '<h2>Deine Website – massgeschneidert und zukunftssicher</h2><p>Unternehmenswebsite, Webshop oder Web-App: Wir entwickeln genau das, was dein Business braucht – mit modernster Technologie und agilem Vorgehen.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-code" style="font-size:2rem;color:var(--primary);"></i><h3>Frontend</h3><p>React, Vue oder klassisch – immer responsive und schnell.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-server" style="font-size:2rem;color:var(--primary);"></i><h3>Backend</h3><p>Django, Node.js, APIs – robust und skalierbar.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-mobile-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Responsive</h3><p>Perfekt auf Handy, Tablet und Desktop.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-rocket" style="font-size:2rem;color:var(--primary);"></i><h3>SEO-optimiert</h3><p>Von Grund auf fur Suchmaschinen gebaut.</p></div></div><p style="font-size:1.1rem;font-weight:600;text-align:center;">Modernste Technologie  |  Agile Entwicklung  |  Faire Preise  |  Personlicher Ansprechpartner</p>',
        'en': '<h2>Your Website – Tailored and Future-Proof</h2><p>Company website, webshop or web app: We develop exactly what your business needs – with cutting-edge technology and agile approach.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-code" style="font-size:2rem;color:var(--primary);"></i><h3>Frontend</h3><p>React, Vue or classic – always responsive and fast.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-server" style="font-size:2rem;color:var(--primary);"></i><h3>Backend</h3><p>Django, Node.js, APIs – robust and scalable.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-mobile-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Responsive</h3><p>Perfect on mobile, tablet and desktop.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-rocket" style="font-size:2rem;color:var(--primary);"></i><h3>SEO Optimized</h3><p>Built for search engines from the ground up.</p></div></div><p style="font-size:1.1rem;font-weight:600;text-align:center;">Latest Technology  |  Agile Development  |  Fair Prices  |  Personal Contact</p>',
        'cta_de': 'Jetzt Projekt anfragen', 'cta_en': 'Request Project'
    },
    'branding': {
        'de': '<h2>Deine Marke – unverwechselbar und stark</h2><p>Vom Logo uber die Farbwelt bis zur kompletten Corporate Identity: Wir machen deine Marke einzigartig und wiedererkennbar.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-paint-brush" style="font-size:2rem;color:var(--primary);"></i><h3>Logo und Farbe</h3><p>Einpragsames Logo und durchdachte Farbpalette.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-font" style="font-size:2rem;color:var(--primary);"></i><h3>Typografie</h3><p>Die perfekte Schrift fur deine Markenpersonlichkeit.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-book" style="font-size:2rem;color:var(--primary);"></i><h3>Brand Guide</h3><p>Komplettes Regelwerk fur konsistenten Markenauftritt.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bullhorn" style="font-size:2rem;color:var(--primary);"></i><h3>Strategie</h3><p>Positionierung, Zielgruppe und Markenstory.</p></div></div>',
        'en': '<h2>Your Brand – Unique and Strong</h2><p>From logo to color palette to complete corporate identity: We make your brand stand out and be memorable.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-paint-brush" style="font-size:2rem;color:var(--primary);"></i><h3>Logo and Color</h3><p>Memorable logo and thoughtful color palette.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-font" style="font-size:2rem;color:var(--primary);"></i><h3>Typography</h3><p>The perfect font for your brand personality.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-book" style="font-size:2rem;color:var(--primary);"></i><h3>Brand Guide</h3><p>Complete rulebook for consistent brand presentation.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bullhorn" style="font-size:2rem;color:var(--primary);"></i><h3>Strategy</h3><p>Positioning, target audience and brand story.</p></div></div>',
        'cta_de': 'Marken-Beratung anfordern', 'cta_en': 'Request Brand Consultation'
    },
    'softwareloesung': {
        'de': '<h2>Deine Software – exakt nach deinen Anforderungen</h2><p>Standard-Software passt nicht? Wir entwickeln individuelle Losungen, die perfekt zu deinen Prozessen passen – von der Analyse bis zur Wartung.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-clipboard-list" style="font-size:2rem;color:var(--primary);"></i><h3>Analyse</h3><p>Wir verstehen deine Prozesse und Anforderungen.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-pencil-ruler" style="font-size:2rem;color:var(--primary);"></i><h3>Konzeption</h3><p>Architektur, UI/UX und Technologie-Stack.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-code" style="font-size:2rem;color:var(--primary);"></i><h3>Entwicklung</h3><p>Agile Entwicklung mit regelma ssigen Reviews.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-life-ring" style="font-size:2rem;color:var(--primary);"></i><h3>Wartung</h3><p>Betreuung, Updates und Weiterentwicklung.</p></div></div>',
        'en': '<h2>Your Software – Exactly to Your Specifications</h2><p>Standard software does not fit? We develop individual solutions perfectly matched to your processes – from analysis to maintenance.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-clipboard-list" style="font-size:2rem;color:var(--primary);"></i><h3>Analysis</h3><p>We understand your processes and requirements.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-pencil-ruler" style="font-size:2rem;color:var(--primary);"></i><h3>Concept</h3><p>Architecture, UI/UX and technology stack.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-code" style="font-size:2rem;color:var(--primary);"></i><h3>Development</h3><p>Agile development with regular reviews.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-life-ring" style="font-size:2rem;color:var(--primary);"></i><h3>Maintenance</h3><p>Support, updates and further development.</p></div></div>',
        'cta_de': 'Beratung vereinbaren', 'cta_en': 'Book Consultation'
    },
    'web-design': {
        'de': '<h2>Web Design, das begeistert und konvertiert</h2><p>Schon allein reicht nicht. Unser Design ist nutzerzentriert, barrierefrei und verkaufsstark – fur hohere Conversion-Rates.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-figma" style="font-size:2rem;color:var(--primary);"></i><h3>UI Design</h3><p>Moderne Interfaces mit Fokus auf Benutzerfreundlichkeit.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-user-check" style="font-size:2rem;color:var(--primary);"></i><h3>UX Design</h3><p>Durchdachte User Journeys fur maximale Conversion.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-mobile-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Mobile First</h3><p>Fur Smartphones optimiert – wo deine Kunden sind.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-palette" style="font-size:2rem;color:var(--primary);"></i><h3>Design System</h3><p>Wiederverwendbare Komponenten.</p></div></div>',
        'en': '<h2>Web Design That Inspires and Converts</h2><p>Pretty is not enough. Our design is user-centered, accessible and conversion-focused – for higher conversion rates.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-figma" style="font-size:2rem;color:var(--primary);"></i><h3>UI Design</h3><p>Modern interfaces focused on usability.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-user-check" style="font-size:2rem;color:var(--primary);"></i><h3>UX Design</h3><p>Thoughtful user journeys for maximum conversion.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-mobile-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Mobile First</h3><p>Optimized for smartphones.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-palette" style="font-size:2rem;color:var(--primary);"></i><h3>Design System</h3><p>Reusable components.</p></div></div>',
        'cta_de': 'Design-Portfolio ansehen', 'cta_en': 'View Portfolio'
    },
    'website-erstellung': {
        'de': '<h2>Deine Website – in Rekordzeit online</h2><p>Professionelle Websites mit modernem Design, schneller Ladezeit und perfekter SEO-Grundlage – in nur 2-4 Wochen.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bolt" style="font-size:2rem;color:var(--primary);"></i><h3>Schnell</h3><p>Bereit in 2-4 Wochen mit Design und Content.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-search" style="font-size:2rem;color:var(--primary);"></i><h3>SEO-ready</h3><p>Meta-Tags, Sitemap, Struktur optimiert.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-shield-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Sicher</h3><p>SSL, Backups, Updates inklusive.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-edit" style="font-size:2rem;color:var(--primary);"></i><h3>Pflegbar</h3><p>Einfaches CMS – du kannst Inhalte selbst andern.</p></div></div>',
        'en': '<h2>Your Website – Online in Record Time</h2><p>Professional websites with modern design, fast loading and perfect SEO foundation – in just 2-4 weeks.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bolt" style="font-size:2rem;color:var(--primary);"></i><h3>Fast</h3><p>Ready in 2-4 weeks with design and content.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-search" style="font-size:2rem;color:var(--primary);"></i><h3>SEO-ready</h3><p>Meta tags, sitemap, structure optimized.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-shield-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Secure</h3><p>SSL, backups, updates included.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-edit" style="font-size:2rem;color:var(--primary);"></i><h3>Editable</h3><p>Simple CMS – you can change content yourself.</p></div></div>',
        'cta_de': 'Website anfragen', 'cta_en': 'Request Website'
    },
    'logo-design': {
        'de': '<h2>Ein Logo, das im Kopf bleibt</h2><p>In 3 Schritten zu deinem perfekten Logo – individuell, professionell, unverwechselbar.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-comments" style="font-size:2rem;color:var(--primary);"></i><h3>Briefing</h3><p>Vision, Werte und Zielgruppe besprechen.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-pencil-ruler" style="font-size:2rem;color:var(--primary);"></i><h3>Design</h3><p>Mehrere Entwurfe mit verschiedenen Stilen.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-sync-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Revision</h3><p>Anpassungen bis alles perfekt sitzt.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-export" style="font-size:2rem;color:var(--primary);"></i><h3>Lieferung</h3><p>PNG, SVG, PDF plus Brand Guide.</p></div></div>',
        'en': '<h2>A Logo That Sticks in Your Mind</h2><p>3 steps to your perfect logo – individual, professional, unmistakable.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-comments" style="font-size:2rem;color:var(--primary);"></i><h3>Briefing</h3><p>Discuss vision, values and target audience.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-pencil-ruler" style="font-size:2rem;color:var(--primary);"></i><h3>Design</h3><p>Multiple drafts with different styles.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-sync-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Revision</h3><p>Adjustments until perfection.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-file-export" style="font-size:2rem;color:var(--primary);"></i><h3>Delivery</h3><p>PNG, SVG, PDF plus Brand Guide.</p></div></div>',
        'cta_de': 'Logo anfragen', 'cta_en': 'Request Logo'
    },
    'marketing-design': {
        'de': '<h2>Design, das dein Marketing aufs nachste Level bringt</h2><p>Social Media, Ads, Print – wir erstellen Designs, die Aufmerksamkeit erregen und konvertieren.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-hashtag" style="font-size:2rem;color:var(--primary);"></i><h3>Social Media</h3><p>Post-Vorlagen, Stories, Highlights.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-ad" style="font-size:2rem;color:var(--primary);"></i><h3>Werbemittel</h3><p>Banner, Anzeigen und Landing Pages.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-print" style="font-size:2rem;color:var(--primary);"></i><h3>Print</h3><p>Flyer, Visitenkarten, Broschuren.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-envelope-open-text" style="font-size:2rem;color:var(--primary);"></i><h3>E-Mail</h3><p>Newsletter-Templates und Signaturen.</p></div></div>',
        'en': '<h2>Design That Takes Your Marketing to the Next Level</h2><p>Social media, ads, print – we create designs that grab attention and convert.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-hashtag" style="font-size:2rem;color:var(--primary);"></i><h3>Social Media</h3><p>Post templates, stories, highlights.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-ad" style="font-size:2rem;color:var(--primary);"></i><h3>Advertising</h3><p>Banners, ads and landing pages.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-print" style="font-size:2rem;color:var(--primary);"></i><h3>Print</h3><p>Flyers, business cards, brochures.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-envelope-open-text" style="font-size:2rem;color:var(--primary);"></i><h3>Email</h3><p>Newsletter templates and signatures.</p></div></div>',
        'cta_de': 'Marketing-Design anfragen', 'cta_en': 'Request Marketing Design'
    },
    'jds-hotels': {
        'de': '<h2>Hotelmanagement – digital, einfach, effizient</h2><p>Zimmerverwaltung, Buchungen, Gastekommunikation und Abrechnung in einer Losung – speziell fur Hotels entwickelt.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bed" style="font-size:2rem;color:var(--primary);"></i><h3>Zimmer</h3><p>Belegungsplan, Reinigung, Kategorien.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-calendar-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Buchungen</h3><p>Reservierungen, Check-in/out.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-euro-sign" style="font-size:2rem;color:var(--primary);"></i><h3>Abrechnung</h3><p>Rechnungen und Statistiken.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-concierge-bell" style="font-size:2rem;color:var(--primary);"></i><h3>Gaste-Service</h3><p>Digitale Gastemappe, Feedback.</p></div></div>',
        'en': '<h2>Hotel Management – Digital, Simple, Efficient</h2><p>Room management, bookings, guest communication and billing in one solution – developed specifically for hotels.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:2rem 0;"><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-bed" style="font-size:2rem;color:var(--primary);"></i><h3>Rooms</h3><p>Occupancy plan, cleaning, categories.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-calendar-alt" style="font-size:2rem;color:var(--primary);"></i><h3>Bookings</h3><p>Reservations, check-in/out.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-euro-sign" style="font-size:2rem;color:var(--primary);"></i><h3>Billing</h3><p>Invoices and statistics.</p></div><div style="background:var(--bg);padding:1.5rem;border-radius:12px;text-align:center;"><i class="fas fa-concierge-bell" style="font-size:2rem;color:var(--primary);"></i><h3>Guest Service</h3><p>Digital guest directory, feedback.</p></div></div>',
        'cta_de': 'Hotel-Software entdecken', 'cta_en': 'Discover Hotel Software'
    },
}

class Command(BaseCommand):
    def handle(self, *args, **options):
        for slug, data in CONTENT.items():
            lp = LandingPage.objects.filter(slug=slug).first()
            if lp:
                lp.content_de = data['de']
                lp.content_en = data['en']
                lp.cta_text_de = data['cta_de']
                lp.cta_text_en = data['cta_en']
                lp.save()
                self.stdout.write(self.style.SUCCESS(f'OK: {slug}'))
        self.stdout.write('Alle 10 Landing-Pages gefullt!')
