# Generated by Django 5.2.1 on 2025-10-21 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_views_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_de',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Inhalt (DE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Inhalt (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(default=1, max_length=200, verbose_name='Titel (DE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Titel (EN)'),
            preserve_default=False,
        ),
    ]
