# Generated by Django 5.2.1 on 2026-02-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='main_image_delete_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image_medium_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image_thumb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
