# Generated by Django 5.2.1 on 2026-02-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_main_image_delete_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image_delete_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImgBB Lösch-URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image_medium_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImgBB Medium URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image_thumb_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImgBB Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ImgBB Bild URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='teaser_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_teasers/'),
        ),
    ]
