# Generated by Django 5.2.1 on 2026-06-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_main_image_delete_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViewTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='blog.blogpost')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('post', 'date')},
            },
        ),
    ]
