# Generated by Django 5.2.1 on 2026-07-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='push_notified_at',
            field=models.DateTimeField(blank=True, help_text="Wann die 'Neuer Artikel'-Push-Benachrichtigung fuer diesen Post gesendet wurde (vom Cron-Check gesetzt).", null=True),
        ),
    ]
