# Generated by Django 5.2.1 on 2026-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_backfill_push_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='main_image_ai_generated',
            field=models.BooleanField(default=False, verbose_name='KI-generiertes Bild'),
        ),
    ]
