# Generated by Django 5.2.1 on 2025-10-24 23:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_openinghour_specialopeninghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_de', models.CharField(max_length=255, verbose_name='Frage (Deutsch)')),
                ('question_en', models.CharField(blank=True, max_length=255, verbose_name='Question (English)')),
                ('short_answer_de', models.TextField(blank=True, verbose_name='Kurzantwort (DE)')),
                ('short_answer_en', models.TextField(blank=True, verbose_name='Short Answer (EN)')),
                ('answer_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Antwort (DE)')),
                ('answer_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Answer (EN)')),
                ('detail_content_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Detailseite Inhalt (DE)')),
                ('detail_content_en', ckeditor.fields.RichTextField(blank=True, verbose_name='Detail Page Content (EN)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Kleinere Zahl = weiter oben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('order', 'question_de'),
            },
        ),
    ]
