# Generated by Django 5.2.1 on 2026-02-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ssoclient_ssosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssoclient',
            name='callback_urls',
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='callback_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
