# Generated by Django 5.2.1 on 2026-02-08 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ssoclient_callback_urls_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSOAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ssoclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scopes', models.ManyToManyField(to='main.ssoscope')),
            ],
        ),
        migrations.AddField(
            model_name='ssosession',
            name='authorization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ssoauthorization'),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='allowed_scopes',
            field=models.ManyToManyField(blank=True, to='main.ssoscope'),
        ),
        migrations.AddIndex(
            model_name='ssoauthorization',
            index=models.Index(fields=['user', 'client'], name='main_ssoaut_user_id_0f2cf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ssoauthorization',
            unique_together={('user', 'client')},
        ),
    ]
