# Generated by Django 5.2.1 on 2026-02-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ssoscope_ssoauthorization_ssosession_authorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOClient_Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ssoclient')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ssoscope')),
            ],
        ),
    ]
