# Generated by Django 5.2.1 on 2026-02-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ssoclient_authorization'),
        ('shop_ourapps', '0031_salebadge_remove_app_sale_badge_image_app_sale_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoclient',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app'),
        ),
    ]
