# Generated by Django 5.2.1 on 2026-07-05 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ssoclient_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Firma')),
                ('marketing_opt_in', models.BooleanField(default=False, verbose_name='Marketing erlaubt')),
                ('marketing_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
