# Generated by Django 5.2.1 on 2026-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('subject', models.CharField(max_length=255, verbose_name='E-Mail-Betreff')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Untertitel')),
                ('content', models.TextField(help_text='HTML-formatierten Inhalt eingeben. Verwende <h2>, <p>, <ul>, <li> etc.', verbose_name='HTML-Inhalt')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Gesendet')], default='draft', max_length=20, verbose_name='Status')),
                ('recipient_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Empfängerzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
                'ordering': ('-created_at',),
            },
        ),
    ]
