# Generated by Django 5.2.1 on 2026-07-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_options_newsletter_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_onesignal_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter OneSignal-Sync'),
        ),
    ]
