# Generated by Django 5.2.1 on 2026-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_last_onesignal_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='OneSignal Player-ID'),
        ),
    ]
