# Generated by Django 5.2.1 on 2026-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_onesignal_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_enabled',
            field=models.BooleanField(default=True, verbose_name='Push-Benachrichtigungen aktiv'),
        ),
    ]
