# Generated by Django 5.2.1 on 2026-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackroomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis (€)')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bild-URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Veröffentlicht')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backroom Produkt',
                'verbose_name_plural': 'Backroom Produkte',
                'ordering': ['order', 'name'],
            },
        ),
    ]
