# Generated by Django 5.2.1 on 2026-07-29 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backroomproduct',
            name='requires_activation',
            field=models.BooleanField(default=False, help_text='Z.B. Softwarelizenzen: Käufer muss nach dem Kauf einen Aktivierungscode erhalten. Siehe backroom/ACTIVATION.md für die Einbindung in den Checkout-Ablauf.', verbose_name='Benötigt Aktivierung'),
        ),
        migrations.CreateModel(
            name='BackroomAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Warum möchtest du Zugang zum Backroom (EK-Shop) erhalten?', verbose_name='Nachricht')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin-Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backroom_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backroom Zugangsanfrage',
                'verbose_name_plural': 'Backroom Zugangsanfragen',
                'ordering': ['-created_at'],
            },
        ),
    ]
