# Generated by Django 5.2.1 on 2026-07-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backroom', '0002_backroomproduct_requires_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backroomproduct',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rabatt Ende'),
        ),
        migrations.AddField(
            model_name='backroomproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='backroomproduct',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rabatt Start'),
        ),
        migrations.AddField(
            model_name='backroomproduct',
            name='uvp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unverbindliche Preisempfehlung - regulärer Verkaufspreis, dient nur zum Vergleich/Anzeige.', max_digits=10, null=True, verbose_name='UVP (€)'),
        ),
        migrations.AlterField(
            model_name='backroomproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Einkaufspreis - das zahlt der Partner im Backroom.', max_digits=10, verbose_name='EK-Preis (€)'),
        ),
    ]
