# Generated by Django 5.2.1 on 2026-07-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backroom', '0003_backroomproduct_discount_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backroomproduct',
            name='description_english',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='backroomproduct',
            name='name_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product name (EN)'),
        ),
        migrations.AlterField(
            model_name='backroomproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung (DE)'),
        ),
        migrations.AlterField(
            model_name='backroomproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Produktname (DE)'),
        ),
    ]
