# Generated by Django 5.2.1 on 2026-06-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdateApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Auto-Update App',
                'verbose_name_plural': 'Auto-Update Apps',
            },
        ),
        migrations.CreateModel(
            name='AutoUpdateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Format: 1.0.0.0', max_length=50)),
                ('release_date', models.DateField()),
                ('download_link', models.URLField(max_length=500)),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='autoupdate.autoupdateapp')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versionen',
                'ordering': ['-release_date'],
                'unique_together': {('app', 'version')},
            },
        ),
    ]
