# Generated by Django 5.2.1 on 2026-07-13 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appissue',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10),
        ),
        migrations.AddField(
            model_name='appissue',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Wann das Problem tatsächlich begann'),
        ),
        migrations.AddField(
            model_name='appissue',
            name='status',
            field=models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20),
        ),
        migrations.AddField(
            model_name='globalissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalissue',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10),
        ),
        migrations.AddField(
            model_name='globalissue',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Wann das Problem tatsächlich begann'),
        ),
        migrations.AddField(
            model_name='globalissue',
            name='status',
            field=models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20),
        ),
    ]
