# Generated by Django 5.2.1 on 2026-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_appissue_title_de_en_description_de_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appissue',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Beschreibung (EN)'),
        ),
        migrations.AlterField(
            model_name='appissue',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titel (EN)'),
        ),
        migrations.AlterField(
            model_name='globalissue',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Beschreibung (EN)'),
        ),
        migrations.AlterField(
            model_name='globalissue',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titel (EN)'),
        ),
    ]
