# Generated by Django 5.2.1 on 2026-06-25 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel (Englisch)')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Beschreibung (Englisch)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='webinar_images/')),
                ('date_time', models.DateTimeField(verbose_name='Datum & Uhrzeit')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Dauer (Minuten)')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Max. Teilnehmer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('recording_url', models.URLField(blank=True, verbose_name='Aufzeichnung (URL)')),
                ('meeting_url', models.URLField(blank=True, verbose_name='Meeting-Link (z.B. Zoom/Teams)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinare',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registriert'), ('cancelled', 'Storniert'), ('attended', 'Teilgenommen'), ('no_show', 'Nicht erschienen')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'verbose_name': 'Webinar-Anmeldung',
                'verbose_name_plural': 'Webinar-Anmeldungen',
                'unique_together': {('webinar', 'user')},
            },
        ),
    ]
