# Generated by Django 5.2.1 on 2026-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anmeldeschluss'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anmeldestart'),
        ),
    ]
