# Generated by Django 5.2.1 on 2026-07-13 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_webinar_registration_end_webinar_registration_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='webinar',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Bild-URL (extern)'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Gast-E-Mail'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gast-Name'),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
