# Generated by Django 5.2.1 on 2026-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug, z.B. 'about-us'", unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title_de', models.CharField(max_length=200, verbose_name='Titel Deutsch')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titel Englisch')),
                ('subheadline_de', models.TextField(blank=True, verbose_name='Unterüberschrift Deutsch')),
                ('subheadline_en', models.TextField(blank=True, verbose_name='Unterüberschrift Englisch')),
                ('content_de', models.TextField(blank=True, verbose_name='Landing Page Text Deutsch')),
                ('content_en', models.TextField(blank=True, verbose_name='Landing Page Text Englisch')),
                ('cta_text_de', models.CharField(blank=True, max_length=100, verbose_name='CTA Text Deutsch')),
                ('cta_link_de', models.URLField(blank=True, verbose_name='CTA Link Deutsch')),
                ('cta_text_en', models.CharField(blank=True, max_length=100, verbose_name='CTA Text Englisch')),
                ('cta_link_en', models.URLField(blank=True, verbose_name='CTA Link Englisch')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
