# Generated by Django 4.2.30 on 2026-06-10 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='content_de',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Landing Page Text Deutsch'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Landing Page Text Englisch'),
        ),
    ]
