# Generated by Django 4.2.30 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_alter_landingpage_content_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='color_accent',
            field=models.CharField(default='#a855f7', help_text='Hex-Farbe, z.B. #a855f7', max_length=7, verbose_name='Akzentfarbe'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='color_primary',
            field=models.CharField(default='#6366f1', help_text='Hex-Farbe, z.B. #6366f1', max_length=7, verbose_name='Primärfarbe'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='custom_css',
            field=models.TextField(blank=True, help_text='CSS-Regeln, die auf diese Seite angewendet werden', verbose_name='Eigenes CSS'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='layout',
            field=models.CharField(choices=[('default', 'Default – Purple Gradient'), ('minimal', 'Minimal – Clean White'), ('showcase', 'Showcase – Dark Product'), ('cards', 'Cards – Grid Layout'), ('dark-hero', 'Dark Hero – Bold Dark'), ('split', 'Split Screen – Left/Right'), ('magazine', 'Magazine – Content Heavy'), ('landing', 'Landing – Form Focus')], default='default', max_length=20, verbose_name='Layout-Vorlage'),
        ),
    ]
