# Generated by Django 4.2.30 on 2026-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_landingpage_color_accent_landingpage_color_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='content_de',
            field=models.TextField(blank=True, help_text='Vollständiges HTML für den Seiteninhalt. Wird 1:1 ausgegeben.', verbose_name='HTML-Inhalt Deutsch'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='content_en',
            field=models.TextField(blank=True, help_text='Full HTML for the page content. Output as-is.', verbose_name='HTML-Inhalt Englisch'),
        ),
    ]
