# Generated by Django 5.2.1 on 2026-07-27 11:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguratorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('content', 'Inhalte'), ('design', 'Design'), ('marketing', 'Marketing & SEO'), ('shop', 'Shop-Funktionen'), ('technik', 'Technik')], default='content', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Einmaliger Aufpreis', max_digits=8)),
                ('site_types', models.CharField(default='onepager,multipage,shop', help_text="Kommagetrennt, z.B. 'shop' für reine Shop-Features", max_length=100)),
                ('techs', models.CharField(default='custom,wordpress,shopify,other', help_text="Kommagetrennt, z.B. 'wordpress,shopify' für reine CMS-Features", max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BasePricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('onepager', 'Onepager'), ('multipage', 'Mehrseitige Homepage'), ('shop', 'Online-Shop')], max_length=20)),
                ('tech', models.CharField(choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Einmaliger Grundpreis. 0 = Preis auf Anfrage', max_digits=8)),
                ('included_pages', models.PositiveIntegerField(default=1, help_text="Inklusive Unterseiten (nur relevant bei 'Mehrseitige Homepage')")),
                ('extra_page_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preis je weiterer Unterseite über die inklusiven hinaus', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['site_type', 'tech'],
                'unique_together': {('site_type', 'tech')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteConfigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('in_review', 'In Prüfung'), ('contacted', 'Kontaktiert'), ('won', 'Gewonnen'), ('lost', 'Verloren')], default='pending', max_length=20)),
                ('site_type', models.CharField(choices=[('onepager', 'Onepager'), ('multipage', 'Mehrseitige Homepage'), ('shop', 'Online-Shop')], max_length=20)),
                ('tech', models.CharField(choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text="Nur bei 'Mehrseitige Homepage' relevant", null=True)),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, help_text='Leer = Preis auf Anfrage', max_digits=10, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True, help_text='Anmerkungen des Interessenten')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne Notizen (nur für Plattform-Admins)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('features', models.ManyToManyField(blank=True, related_name='requests', to='website_configurator.configuratorfeature')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
