# Generated by Django 5.2.1 on 2026-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_configurator', '0002_seed_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepricingoption',
            name='tech',
            field=models.CharField(choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('squarespace', 'Squarespace'), ('webflow', 'Webflow'), ('typo3', 'TYPO3'), ('joomla', 'Joomla'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('other', 'Anderes System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configuratorfeature',
            name='category',
            field=models.CharField(choices=[('content', 'Inhalte'), ('design', 'Design'), ('marketing', 'Marketing & SEO'), ('shop', 'Shop-Funktionen'), ('technik', 'Technik'), ('legal', 'Recht & Sicherheit')], default='content', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuratorfeature',
            name='techs',
            field=models.CharField(default='custom,wordpress,wix,squarespace,webflow,typo3,joomla,shopify,magento,other', help_text="Kommagetrennt, z.B. 'wordpress,shopify' für reine CMS-Features", max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='estimated_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leer = Preis auf Anfrage bzw. noch nicht berechnet', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='site_type',
            field=models.CharField(blank=True, choices=[('onepager', 'Onepager'), ('multipage', 'Mehrseitige Homepage'), ('shop', 'Online-Shop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf (nicht abgeschlossen)'), ('pending', 'Ausstehend'), ('in_review', 'In Prüfung'), ('contacted', 'Kontaktiert'), ('won', 'Gewonnen'), ('lost', 'Verloren')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='tech',
            field=models.CharField(blank=True, choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('squarespace', 'Squarespace'), ('webflow', 'Webflow'), ('typo3', 'TYPO3'), ('joomla', 'Joomla'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('other', 'Anderes System')], max_length=20),
        ),
    ]
