# Generated by Django 5.2.1 on 2026-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_configurator', '0004_expand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfigrequest',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Kunde hat beim verbindlichen Absenden AGB/Datenschutz akzeptiert'),
        ),
        migrations.AddField(
            model_name='websiteconfigrequest',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='phone',
            field=models.CharField(help_text='Pflichtfeld - für Rückfragen zum verbindlichen Auftrag', max_length=50),
        ),
    ]
