# Generated by Django 5.2.1 on 2026-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_configurator', '0008_seed_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepricingoption',
            name='tech',
            field=models.CharField(choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('squarespace', 'Squarespace'), ('webflow', 'Webflow'), ('typo3', 'TYPO3'), ('joomla', 'Joomla'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='tech',
            field=models.CharField(blank=True, choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('squarespace', 'Squarespace'), ('webflow', 'Webflow'), ('typo3', 'TYPO3'), ('joomla', 'Joomla'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20),
        ),
    ]
