# Generated by Django 5.2.1 on 2026-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_configurator', '0010_cleanup_magento_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepricingoption',
            name='tech',
            field=models.CharField(choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteconfigrequest',
            name='tech',
            field=models.CharField(blank=True, choices=[('custom', 'Programmiert (Custom Code)'), ('wordpress', 'WordPress'), ('wix', 'Wix'), ('shopify', 'Shopify'), ('other', 'Anderes System')], max_length=20),
        ),
    ]
