# Generated by Django 5.2.1 on 2025-05-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatelink',
            name='app',
        ),
    ]
