# Generated by Django 5.2.1 on 2025-05-14 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0007_affiliatecode_discountcode_remove_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='discount_percent',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
