# Generated by Django 5.2.1 on 2025-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0011_app_created_at_app_is_active_app_link_app_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepartner',
            name='commission_percent',
            field=models.PositiveIntegerField(default=3, help_text='Provision in Prozent'),
        ),
    ]
