# Generated by Django 5.2.1 on 2025-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0013_wallet_walletcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
