# Generated by Django 5.2.1 on 2025-05-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0014_wallet_pending_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AffiliateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.affiliatepartner')),
            ],
        ),
    ]
