# Generated by Django 5.2.1 on 2025-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0017_voucher_voucherorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='android_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='linux_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='macos_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='windows_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
