# Generated by Django 5.2.1 on 2025-07-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0020_order_city_order_zip_code_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Received'), ('completed', 'Paid'), ('return', 'Return'), ('cancelled', 'Canceled'), ('shipped', 'Back at Joel Digitals'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered'), ('Finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
