# Generated by Django 5.2.1 on 2025-07-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Paid', 'Paid'), ('Return', 'Return'), ('Canceled', 'Canceled'), ('Back', 'Back at Joel Digitals'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
