# Generated by Django 5.2.1 on 2025-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Rabatt in Prozent (0-100)'),
        ),
    ]
