# Generated by Django 5.2.1 on 2025-08-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0023_app_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
