# Generated by Django 5.2.1 on 2025-08-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0024_alter_app_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
