# Generated by Django 5.2.1 on 2025-08-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0025_order_account_holder_order_bank_name_order_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='product_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
