# Generated by Django 5.2.1 on 2025-10-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0026_app_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
