# Generated by Django 5.2.1 on 2025-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0027_app_description_english_app_name_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
