# Generated by Django 5.2.1 on 2025-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0028_orderitem_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
