# Generated by Django 5.2.1 on 2025-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0029_orderitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='is_black_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='is_christmas_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='is_cyber_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='sale_badge_image',
            field=models.ImageField(blank=True, null=True, upload_to='sale_badges/'),
        ),
    ]
