# Generated by Django 5.2.1 on 2026-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0031_salebadge_remove_app_sale_badge_image_app_sale_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='single_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
