# Generated by Django 5.2.1 on 2026-06-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0032_orderitem_single_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Automatisch auf 30 Min nach registration_code_sent_at gesetzt', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Registrierungscode für den Versand', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_code_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, wann der Registrierungscode gesendet wurde', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_email_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Geplante Zeit zum Versand der Review-Email (12-30 Stunden nach delivered_at)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, wann Review-Email gesendet wurde', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Paid', 'Paid'), ('Return', 'Return'), ('Canceled', 'Canceled'), ('Back', 'Back at Joel Digitals'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Finished', 'Finished')], default='Received', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_changed', 'Status geändert'), ('registration_code_sent', 'Registrierungscode gesendet'), ('auto_delivered', 'Automatisch als geliefert markiert'), ('review_email_scheduled', 'Review-Email geplant'), ('review_email_sent', 'Review-Email gesendet')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='shop_ourapps.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
