# Generated by Django 4.2.30 on 2026-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0035_app_refundable_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Admin-Notiz'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('not_working', 'App funktioniert nicht / Startet nicht'), ('technical_issue', 'Technisches Problem (Bug, Absturz)'), ('install_failed', 'Installation fehlgeschlagen'), ('wrong_product', 'Falsches Produkt erhalten'), ('duplicate', 'Versehentlich doppelt bestellt'), ('wrong_version', 'Falsche Version / Plattform'), ('not_as_described', 'Entspricht nicht der Beschreibung'), ('missing_feature', 'Erwartete Funktion fehlt'), ('language_issue', 'Sprachproblem / Falsche Sprache'), ('changed_mind', 'Meinung geändert / nicht mehr benötigt'), ('price_issue', 'Preisproblem / günstiger anderswo'), ('other', 'Sonstiges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Erstattungsbetrag (€)'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(blank=True, help_text='z.B. Stripe, PayPal, Wallet, Überweisung', max_length=50, verbose_name='Erstattungsmethode'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstattet am'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_label_url',
            field=models.URLField(blank=True, verbose_name='Retourenschein-URL'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend – Prüfung läuft'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('processing', 'In Bearbeitung'), ('completed', 'Abgeschlossen – Erstattet')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='tracking_carrier',
            field=models.CharField(blank=True, help_text='z.B. DHL, UPS, DPD, Hermes', max_length=50, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sendungsnummer'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Direktlink zur Sendungsverfolgung', verbose_name='Tracking-URL'),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='carrier',
            field=models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('DPD', 'DPD'), ('Hermes', 'Hermes'), ('GLS', 'GLS'), ('FedEx', 'FedEx'), ('PostAG', 'Österreichische Post'), ('Swiss', 'Swiss Post'), ('custom', 'Sonstiger Carrier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Voraussichtliche Lieferung'),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Wenn leer, wird auto-generiert'),
        ),
    ]
