# Generated by Django 4.2.30 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0038_returnrequest_return_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sepa_mandate_date',
            field=models.DateTimeField(blank=True, help_text='Datum des SEPA-Mandats', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sepa_mandate_ref',
            field=models.CharField(blank=True, help_text='SEPA-Mandatsreferenz', max_length=64, null=True),
        ),
    ]
