# Generated by Django 4.2.30 on 2026-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0039_order_sepa_mandate_date_order_sepa_mandate_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='exchangeable',
            field=models.BooleanField(default=False, help_text='Kann diese App umgetauscht werden?'),
        ),
    ]
