# Generated by Django 5.2.1 on 2026-06-11 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0040_app_exchangeable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_physical',
            field=models.BooleanField(default=False, help_text='Ist dies ein physisches Produkt?'),
        ),
        migrations.AddField(
            model_name='app',
            name='requires_shipping',
            field=models.BooleanField(default=False, help_text='Benötigt dieses Produkt einen Versand?'),
        ),
        migrations.AddField(
            model_name='app',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Versandkosten (einmalig pro Bestellung)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='stock',
            field=models.IntegerField(default=0, help_text='Lagerbestand (0 = nicht auf Lager)'),
        ),
        migrations.AddField(
            model_name='app',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
