# Generated by Django 5.2.1 on 2026-06-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0041_app_is_physical_app_requires_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateMarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.CharField(max_length=200, verbose_name='Titel (DE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('file_de', models.FileField(upload_to='affiliate/marketing/', verbose_name='Werbematerial (DE) ZIP')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='affiliate/marketing/', verbose_name='Marketing Material (EN) ZIP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Werbematerial',
                'verbose_name_plural': 'Werbematerialien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='affiliate/invoices/', verbose_name='Rechnungsdatei')),
                ('is_credited', models.BooleanField(default=False, verbose_name='Gutgeschrieben')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shop_ourapps.affiliatepartner')),
            ],
            options={
                'verbose_name': 'Affiliate-Rechnung',
                'verbose_name_plural': 'Affiliate-Rechnungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
