# Generated by Django 5.2.1 on 2026-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0042_affiliatemarketingmaterial_affiliateinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateinvoice',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('provision', 'Provision'), ('bonus', 'Bonus'), ('refund', 'Rückerstattung'), ('other', 'Sonstiges')], default='provision', max_length=20, verbose_name='Rechnungstyp'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='pdf_generated',
            field=models.BooleanField(default=False, verbose_name='PDF erstellt'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='USt-ID'),
        ),
        migrations.AddField(
            model_name='affiliateinvoice',
            name='zip_code',
            field=models.CharField(default='', max_length=20, verbose_name='PLZ'),
        ),
    ]
