# Generated by Django 5.2.1 on 2026-06-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0043_affiliateinvoice_address_affiliateinvoice_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app'),
        ),
    ]
