# Generated by Django 5.2.1 on 2026-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0044_alter_orderitem_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name_override',
            field=models.CharField(blank=True, max_length=255, verbose_name='Produktname (manuell)'),
        ),
    ]
