# Generated by Django 5.2.1 on 2026-06-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0045_orderitem_name_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-Pfad')),
                ('greeting_name', models.CharField(help_text='z.B. Max, Anna, Chef', max_length=100, verbose_name='Anrede-Name')),
                ('headline', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('subtitle', models.TextField(blank=True, verbose_name='Unterüberschrift')),
                ('cta_text', models.CharField(default='Jetzt kaufen', max_length=100, verbose_name='Button-Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_ourapps.app', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Custom Landing Page',
                'verbose_name_plural': 'Custom Landing Pages',
            },
        ),
    ]
