# Generated by Django 5.2.1 on 2026-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0048_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
    ]
