# Generated by Django 5.2.1 on 2026-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0049_withdrawalrequest_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='delivery_time',
            field=models.CharField(blank=True, default='', help_text='z.B. 2-3 Werktage', max_length=100),
        ),
    ]
