# Generated by Django 5.2.1 on 2026-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0051_watchlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='preorder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vorbestellungsbeginn'),
        ),
    ]
