# Generated by Django 5.2.1 on 2026-06-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0052_app_preorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('description_english', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available_for_purchase', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release-Datum')),
                ('preorder_date', models.DateField(blank=True, null=True, verbose_name='Vorbestellungsbeginn')),
                ('discount_start', models.DateTimeField(blank=True, null=True)),
                ('discount_end', models.DateTimeField(blank=True, null=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_ourapps.salebadge')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.package'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.package'),
        ),
        migrations.CreateModel(
            name='PackageApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.package')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('package', 'app')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='apps',
            field=models.ManyToManyField(blank=True, through='shop_ourapps.PackageApp', to='shop_ourapps.app'),
        ),
    ]
