# Generated by Django 5.2.1 on 2026-06-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0053_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.package'),
        ),
        migrations.AddField(
            model_name='package',
            name='stock',
            field=models.IntegerField(default=0, help_text='Lagerbestand (0 = nicht auf Lager)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_ourapps.app'),
        ),
    ]
