# Generated by Django 5.2.1 on 2026-06-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0054_cartitem_package_package_stock_alter_cartitem_app'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='shop_ourapps.package'),
        ),
        migrations.AlterField(
            model_name='watchlistentry',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='shop_ourapps.app'),
        ),
    ]
