# Generated by Django 5.2.1 on 2026-06-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0055_alter_watchlistentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_time',
            field=models.CharField(blank=True, default='', help_text='z.B. 2-3 Werktage', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='is_physical',
            field=models.BooleanField(default=False, help_text='Ist dies ein physisches Produkt?'),
        ),
        migrations.AddField(
            model_name='package',
            name='requires_shipping',
            field=models.BooleanField(default=False, help_text='Benötigt dieses Paket einen Versand?'),
        ),
        migrations.AddField(
            model_name='package',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Versandkosten (einmalig pro Bestellung)', max_digits=6, null=True),
        ),
    ]
