# Generated by Django 5.2.1 on 2026-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0056_package_delivery_time_package_is_physical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image_url',
            field=models.URLField(blank=True, help_text='Externe Bild-URL (z.B. von ibb.co) - hat Vorrang vor dem Datei-Upload und entlastet den Server.', max_length=500, null=True, verbose_name='ImgBB Bild-URL'),
        ),
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, help_text='Externe Bild-URL (z.B. von ibb.co) - hat Vorrang vor dem Datei-Upload und entlastet den Server.', max_length=500, null=True, verbose_name='ImgBB Bild-URL'),
        ),
    ]
