# Generated by Django 5.2.1 on 2026-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0057_app_image_url_package_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jds_customer_id',
            field=models.CharField(blank=True, help_text='Kunden-ID in JDS Management (aus der Sync-API)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='jds_sync_error',
            field=models.TextField(blank=True, help_text='Letzter Fehler beim Sync mit JDS Management (falls vorhanden)'),
        ),
        migrations.AddField(
            model_name='order',
            name='jds_synced_at',
            field=models.DateTimeField(blank=True, help_text='Wann diese Bestellung zuletzt erfolgreich an JDS Management übertragen wurde', null=True),
        ),
    ]
