# Generated by Django 5.2.1 on 2026-07-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0058_order_jds_customer_id_order_jds_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_ourapps.voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_in_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='shop_ourapps.order'),
        ),
    ]
