# Generated by Django 5.2.1 on 2026-07-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0062_jds_management_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='jds_customer_id',
            field=models.CharField(blank=True, help_text='Kundennummer in JDS Management (aus der Sync-API)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='jds_sync_error',
            field=models.TextField(blank=True, help_text='Letzter Fehler beim Sync mit JDS Management (falls vorhanden)'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='jds_synced_at',
            field=models.DateTimeField(blank=True, help_text='Wann diese Kundendaten zuletzt erfolgreich an JDS Management uebertragen wurden', null=True),
        ),
    ]
