# Generated by Django 5.2.1 on 2026-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_ourapps', '0063_customerinfo_jds_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='jds_product_id',
            field=models.CharField(blank=True, help_text='Interne numerische Produkt-ID in JDS Management (fuer Stock-Updates per PATCH /api/v2/products/<id>/ - wird von sync_stock() gesetzt, product_number ist dort NICHT der URL-Schluessel).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='jds_customer_number',
            field=models.CharField(blank=True, help_text='Menschenlesbare Kundennummer in JDS Management (dem Kunden anzuzeigen)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='jds_customer_id',
            field=models.CharField(blank=True, help_text='Interne Kunden-ID in JDS Management (aus der Sync-API, fuer Updates)', max_length=100, null=True),
        ),
    ]
