# Generated by Django 5.2.1 on 2026-07-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backroom', '0001_initial'),
        ('shop_ourapps', '0064_app_jds_product_id_customerinfo_jds_customer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='backroom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backroom.backroomproduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='backroom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backroom.backroomproduct'),
        ),
    ]
